name: upgrade-main

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Upgrade Deps
        uses: p6m7g8-actions/next-upgrade@main
        with:
          gh_token: ${{ secrets.P6_PGOLLUCCI_GH_TOKEN }}